Changes and developments towards xgboost model evaluation
AliceO2Group/TPCwithDNN pull request #100
Opened 2021-06-30 11:36 UTC by ehellbar

This is based on #99 

Further minor and major changes to the framework. Goal is to provide the validation data which can be used to extensively evaluate trained models. Functionality is extended towards the use of a batch system, e.g. adding more command line arguments.

2021-07-12 09:14 UTC, saganatt commented on tpcwithdnn/data_loader.py
> +                                          data / (scipy.constants.e * NELE_PER_ADC))) # C -> ADC
which one is side A, and which one C? (Both your comments say C)

2021-07-12 09:14 UTC, saganatt commented on tpcwithdnn/data_loader.py
> +                                          data / (scipy.constants.e * NELE_PER_ADC))) # C -> ADC
Is this already some hidden downsampling?

2021-07-12 09:49 UTC, saganatt commented on tpcwithdnn/data_loader.py
> +def get_input_names_oned_idc():
I use `one_idc` instead of `oned_idc` in function names, let's stick to one convention throghout the code

2021-07-12 09:53 UTC, saganatt commented on tpcwithdnn/data_loader.py
> -    vec_sel_in_z = (input_z_range[0] <= vec_z_pos) & (vec_z_pos < input_z_range[1])
so now we ignore the z-range set by the user? I see only downsampling below, but you don't restrict z in any way...

2021-07-12 09:57 UTC, saganatt commented on tpcwithdnn/data_validator.py
> +                    if ind_ev[1] != self.mean_ids[index_mean_id]:
why just not get the mean id straight from the for in line 149?

2021-07-12 09:57 UTC, saganatt commented on tpcwithdnn/data_validator.py
> +                                            counter, self.mean_ids[index_mean_id], irnd)
same here

2021-07-12 09:57 UTC, saganatt commented on tpcwithdnn/data_validator.py
> +                                            counter, self.mean_ids[index_mean_id], irnd)
and here

2021-07-12 09:58 UTC, saganatt commented on tpcwithdnn/data_validator.py
>              counter = 0
you can use index_mean_id as counter, no?

2021-07-12 10:01 UTC, saganatt commented on tpcwithdnn/xgboost_optimiser.py
> +        downsample = self.config.downsample if partition != "validation" else False
so we downsample the apply partition as well?

2021-07-12 10:03 UTC, saganatt commented on tpcwithdnn/xgboost_optimiser.py
> +        xgboost.plot_importance(model, importance_type='gain', xlabel='gain', log=True,
The same code repeated 3 times - can we put this in a loop over importance types / filenames?

2021-07-12 10:03 UTC, saganatt commented on tpcwithdnn/xgboost_optimiser.py
> +        xgboost.plot_importance(model, importance_type='gain', xlabel='gain', log=True,
lines 86-124

2021-07-12 10:08 UTC, saganatt commented on tpcwithdnn/xgboost_optimiser.py
> +            for i in range(0, len(list(score_total_gain.values()))):
it is more pythonic to use zips instead of range. Perhaps it can be simplified a bit

2021-07-12 10:10 UTC, saganatt requested changes
Hi @ehellbar  I left some comments - mainly the coding style.
See also my comments on downsampling and z-range, I am not sure the selection is correct now.

2021-07-14 11:54 UTC, ehellbar commented on tpcwithdnn/data_loader.py
> +                                          data / (scipy.constants.e * NELE_PER_ADC))) # C -> ADC
The comments say C ->ADC which means charge (units of Coulomb) to ADC value (digitized value). For the current data, the IDCs are in units of Coulomb which results in number of the order of 1e-12. I renormalize to ADC values here to get number of the order of 10000s.

2021-07-14 11:55 UTC, ehellbar commented on tpcwithdnn/data_loader.py
> +                                          data / (scipy.constants.e * NELE_PER_ADC))) # C -> ADC
It is just some renormalization to ADC values (see comment above), or does your comment refer to some other place in the code?

2021-07-15 08:07 UTC, saganatt commented
One more nitpick; we can rename 'input_z_range` to just `z_range`, so it won't be confusing that the output is constrained as well

2021-07-20 09:28 UTC, merged