Change downsample fraction to number of points, and make fourier coefficients configurable
AliceO2Group/TPCwithDNN pull request #107
Opened 2021-09-03 06:41 UTC by saganatt

2021-09-03 14:24 UTC, ehellbar requested changes

2021-09-03 14:24 UTC, ehellbar commented on tpcwithdnn/common_settings.py
> +        self.num_fourier_coeffs_apply = data_param["num_fourier_coeffs_apply"]
Wouldn't  "num_fourier_coeffs_pred" be a more precise name for this? "apply" could lead to the false conclusion that these would be used only in the function which you called apply. But this should be rather used at all stages after the training where a prediction is made.

2021-09-03 14:24 UTC, ehellbar commented on tpcwithdnn/data_loader.py
> +    if not is_train:
Could the argument `is_train` be removed when simply comparing the numbers  `num_fourier_coeffs_apply` and `num_fourier_coeffs_train`?
`if num_fourier_coeffs_apply < num_fourier_coeffs_train`

Also, we should make a safety cross check whether `num_fourier_coeffs_apply` is bigger than `num_fourier_coeffs_train`.

2021-09-03 15:03 UTC, saganatt commented on tpcwithdnn/common_settings.py
> +        self.num_fourier_coeffs_apply = data_param["num_fourier_coeffs_apply"]
For me apply == predict, I didn't differ between those terms.
In the configuration file there are several 'train', 'validation', 'nd_val' and 'apply' parameters. So 'apply' seems consistent for me.
Do you want "num_fourier_coeffs_pred" to be used for the "validation" partition as well? And for the ND validation? Then, perhaps "num_fourier_coeffs_val_apply"?

2021-09-03 15:06 UTC, saganatt commented on tpcwithdnn/data_loader.py
> +    if not is_train:
ok, I was just thinking that for the training we do not care about "num_fourier_coeffs_apply" at all? I.e. we don't want to zero any part of the vector?

2021-09-03 15:08 UTC, ehellbar commented on tpcwithdnn/common_settings.py
> +        self.num_fourier_coeffs_apply = data_param["num_fourier_coeffs_apply"]
ok, then leave it as it is.

2021-09-03 15:10 UTC, ehellbar commented on tpcwithdnn/common_settings.py
> +        self.num_fourier_coeffs_apply = data_param["num_fourier_coeffs_apply"]
Can you please add a command line option to define `num_fourier_coeffs_apply`?

2021-09-03 15:21 UTC, ehellbar commented on tpcwithdnn/data_loader.py
> +    if not is_train:
In that case, you could just pass the same number twice. You anyway make the check for the partition in the get_data function of the xgb optimiser (line 171), so instead of an additional function parameter `is_train`, you could define `n_coeffs_apply = self.config.num_fourier_coeffs_train`.

2021-09-03 15:24 UTC, saganatt commented on tpcwithdnn/data_loader.py
> +    if not is_train:
ok

2021-09-07 09:29 UTC, ehellbar requested changes

2021-09-07 09:29 UTC, ehellbar commented on tpcwithdnn/data_loader.py
> +def get_fourier_coeffs(vec_oned_idc, is_train, num_fourier_coeffs_train, num_fourier_coeffs_apply):
`is_train` argument can be removed here and in all places where this function is used.

2021-09-07 09:29 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +                                                           self.config.num_fourier_coeffs_apply)
this should be `num_fourier_coeffs_apply`

2021-09-07 14:09 UTC, ehellbar requested changes

2021-09-07 14:09 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +        dft_coeffs = get_fourier_coeffs(vec_fluc_oned_idc, True, # assumed train (all) coefficients
here the `is_train` argument is still used. Please check all occurrences for code consistency. Thanks!

2021-09-07 14:38 UTC, saganatt commented on tpcwithdnn/idc_data_validator.py
> +        dft_coeffs = get_fourier_coeffs(vec_fluc_oned_idc, True, # assumed train (all) coefficients
Sorry, I needed to do other stuff in the meantime. Now I fixed and tested the full workflow, so now it is hopefully fine :-)

2021-09-07 14:43 UTC, ehellbar requested changes

2021-09-07 14:43 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
Why change it here? `num_fourier_coeffs_apply` is introduced to study the effect of the number of Fourier coefficients on the prediction performance. The way we will study it is by looking at the predictions in the nd space (nd validation), so this is the actual place where this variable is really really relevant.

2021-09-08 09:22 UTC, saganatt commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
ok, so we do not need to store all Fourier coefficients for validation? I.e. we will study them only with predictions?

Because the users can run the nd validation with and without validating the model predictions, in the second case I would then put all Fourier coefficients in the file...?

2021-09-08 11:49 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
yes, you are right. At the moment, there is also the possibility to dump only the input data, for which we should put all coefficients. We should disentangle this for the future by providing the input in TTrees including the coefficients from the beginning. I will work on that. 

So for the moment, I would simply put there the correct variable `num_fourier_coeffs_apply` and let the user decide what he wants to do by defining the number of train / apply coefficients and if he wants to have the model prediction or not either in the config file or by the command line.

2021-09-08 12:22 UTC, saganatt commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
ok, one more doubt: in line 126 we use `np.tile((dft_coeffs[0]), vec_z_pos.size)`, shouldn't we drop `[0]` to store all coefficients instead of the first one?

2021-09-08 13:14 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
the way the df is organized is per space point, i.e. each row is a different space point. It makes no sense to assign each coefficient to a different space point. We already talked about this, the length of the space-point and corresponding other vectors is different from the 1D IDC / Fourier coefficient vector. 

There are two possibilities if you want to have to coefficients in the same df / tree:
1) put there vectors of space-points / coefficients in each row, which can have different length. This is possible with a TTree, don't know about pandas.
2) put n columns per row for n coefficients, which will be the same for every space point for a given map.
I have to think about how we will look at the validation of the model to decide what will be the best way.

For now, we only store the 0th coefficient because it is correlated to deltaSC and the 0D IDC fluctuation.

2021-09-08 13:24 UTC, saganatt commented on tpcwithdnn/idc_data_validator.py
> +                                        self.config.num_fourier_coeffs_train)
ok, I see. Yes, I remember, I got a bit confused here.
Ok, let's then finish this PR, and we will later follow on both the correction input (TTrees) and the validation format.

2021-09-08 13:29 UTC, ehellbar approved these changes

2021-09-08 13:30 UTC, ehellbar commented
ok.
can you merge #107 and #108 in the order that you prefer, please?

2021-09-08 13:37 UTC, merged