Use hadd in validator to merge validation files
AliceO2Group/TPCwithDNN pull request #116
Opened 2021-12-08 17:46 UTC by saganatt

Hi @ehellbar this is the hadd change you requested.
It merges data per mean id.
Let me know if this is what you meant. :-)

2021-12-13 15:24 UTC, ehellbar requested changes
Hello @saganatt ,

thanks a lot for the implementation. Just two minor requests.

Regards,
Ernst

2021-12-13 15:24 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +            merged_file_name = "%s/treeValidation_mean%.2f_nEv%d.root" %\
I changed the file name to ```validation_mean%.2f_nEv%d.root```, see line 141. Can you adjust the merged file name accordingly?

2021-12-13 15:24 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +            #for out_file in out_file_names: # TODO: Do we want to preserve the partial files?
I think we can safely delete the partial data.

2021-12-13 15:38 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
> +            #for out_file in out_file_names: # TODO: Do we want to preserve the partial files?
Here we might then also consider to put all partial files into the same folder in order to avoid having the folders with the indices left after deleting the files, or also delete the folders.

2021-12-13 16:00 UTC, ehellbar commented
Hello @saganatt ,

in the previous PR https://github.com/AliceO2Group/TPCwithDNN/pull/112#discussion_r756104587 you mentioned similar merging times for ```tpcwithdnn.hadd``` and ```hadd``` using ROOT.

I performed a quick benchmark on my laptop for the nd validation data:

**Using tpcwithdnn.hadd**
```
(Singularity) hellbaer@hellbaer-Thinkpad:~/data/NOTESData/JIRA/ATO-490$ time python /home/hellbaer/software/TPCwithDNN/tpcwithdnn/steer_analysis.py --nestimators 100 --maxdepth 3 --cache-train --cache-events 100 --rndaugment --dnpoints 10 --ntrain1d 100 --nval 10 --docreatendvaldata
...
Arguments provided: Namespace(cache_events=100, cache_train=True, config_file='config_model_parameters.yml', docreatendvaldata=True, downsample_npoints=10, max_depth=3, n_estimators=100, nd_val_events=10, rndaugment=True, steer_file='default.yml', train_events_oned=100)
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/common_settings.py:64:
Inputs active for training: (SCMean, SCFluctuations)=(1, 1)
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/common_settings.py:247:
XGBoostSettings::Init
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/common_settings.py:303:
I am processing the configuration phi180_r33_z33_nest100_depth3_lr1.000_tm-hist_g0.00_weight1.0_d0.0_sub0.80_colTree0.8_colLvl1.0_colNode1.0_a0.0_l0.00005_scale1.0_base0.50_pred_doR1_dophi0_doz0_input_z0.0-251.0_rndaugment_dpoints10_ftrain40
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/xgboost_optimiser.py:39:
XGBoostOptimiser::Init
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:38:
IDCDataValidator::Init
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/common_settings.py:142:
Processing 300 events
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:150:
DataValidator::create_data
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 0 [0, 800]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 1 [0, 801]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 2 [0, 802]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 3 [0, 803]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 4 [0, 804]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 5 [0, 805]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 6 [0, 806]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 7 [0, 807]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 8 [0, 808]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:179:
processing event: 9 [0, 809]
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/hadd.py:63:
Merging tree validation
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/debug_utils.py:22:
Elapsed time for merging nd validation data: 0m 21s
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/idc_data_validator.py:194:
Merged trees for mean 0 written in trees/phi180_r33_z33_nest100_depth3_lr1.000_tm-hist_g0.00_weight1.0_d0.0_sub0.80_colTree0.8_colLvl1.0_colNode1.0_a0.0_l0.00005_scale1.0_base0.50_pred_doR1_dophi0_doz0_input_z0.0-251.0_rndaugment_dpoints10_ftrain40/treeValidation_mean1.00_nEv100.root
...
All trees written in trees/phi180_r33_z33_nest100_depth3_lr1.000_tm-hist_g0.00_weight1.0_d0.0_sub0.80_colTree0.8_colLvl1.0_colNode1.0_a0.0_l0.00005_scale1.0_base0.50_pred_doR1_dophi0_doz0_input_z0.0-251.0_rndaugment_dpoints10_ftrain40
INFO     in /home/hellbaer/software/TPCwithDNN/tpcwithdnn/steer_analysis.py:283:
Program finished.

real    2m36.174s
user    3m4.266s
sys     0m6.009s
```

**Using ROOT hadd**
```
(Singularity) hellbaer@hellbaer-Thinkpad:~/data/NOTESData/JIRA/ATO-490/trees/phi180_r33_z33_nest100_depth3_lr1.000_tm-hist_g0.00_weight1.0_d0.0_sub0.80_colTree0.8_colLvl1.0_colNode1.0_a0.0_l0.00005_scale1.0_base0.50_pred_doR1_dophi0_doz0_input_z0.0-251.0_rndaugment_dpoints10_ftrain40$ time hadd -f validation_mean1.00_nEv100.root parts/*/validation_mean1.00_nEv100.root
hadd Target file: validation_mean1.00_nEv100.root
hadd compression setting for all output: 1
hadd Source file 1: parts/800/validation_mean1.00_nEv100.root
hadd Source file 2: parts/801/validation_mean1.00_nEv100.root
hadd Source file 3: parts/802/validation_mean1.00_nEv100.root
hadd Source file 4: parts/803/validation_mean1.00_nEv100.root
hadd Source file 5: parts/804/validation_mean1.00_nEv100.root
hadd Source file 6: parts/805/validation_mean1.00_nEv100.root
hadd Source file 7: parts/806/validation_mean1.00_nEv100.root
hadd Source file 8: parts/807/validation_mean1.00_nEv100.root
hadd Source file 9: parts/808/validation_mean1.00_nEv100.root
hadd Source file 10: parts/809/validation_mean1.00_nEv100.root
hadd Target path: validation_mean1.00_nEv100.root:/

real    0m0.871s
user    0m0.522s
sys     0m0.186s
```

As you can see, the ROOT hadd seems to be much faster, ~20 seconds vs <1 second. Can you confirm these observations?

2021-12-13 16:20 UTC, saganatt commented
Actually your debug for validator shows: Elapsed time for merging nd validation data: 0m 21s ;-)

2021-12-13 16:30 UTC, ehellbar commented
Yes, I put the timer around  line 185 ```hadd(out_file_names, merged_file_name)```, so only the merging should be timed.

2021-12-14 11:38 UTC, saganatt commented
Hi @ehellbar - I checked today on aliceml.

And finally I understand. I used hadd.C, which also works in 20 s like the python version.
You use the executable hadd - indeed, it works very fast , ~1 s for me as well. I didn't know about this one... well, the difference between the compiled and the interpreted code, apparently ;-)

So then, we can indeed drop this PR for now.

2021-12-15 11:07 UTC, ehellbar commented
Hello @saganatt ,

thank you for checking. Agreed, I will close the PR.

2021-12-15 11:07 UTC, closed without merging