Added XGB and NN for 1D correction
AliceO2Group/TPCwithDNN pull request #126
Opened 2022-07-25 08:40 UTC by babaht

Added XGB and NN for 1D correction

2022-10-12 14:24 UTC, ehellbar requested changes
Hello Hitoshi,

I finally went through the PR, thanks a lot for the work. I just added a few comments.

Two general comments:
1) Please always make a proper git pull --rebase of the master branch (instead of merging the master branch into yours) to avoid conflicts and unnecessary merge commits. This happened also in you last merge commit, where you merged my latest PR with the new notebook.
2) Please follow the general code conventions and syntax, e.g. variable names should look like the following: my_variable instead of myVariable, my_function instead of myFunction, etc. Please change the code accordingly.

Regards,
Ernst

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/common_settings.py
> +            self.opt_usederivative[1], self.opt_usederivative[2])
I think the proper standard python syntax that we use aligns the variables, not the bracket

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/data_loader.py
The directory structure was agreed on. This is our convention which was always used. Please use the same convention.

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
>          df_single_map["flucCorrRPred"] = loaded_model.predict(inputs).astype('float32')
Here you can add a new option in the config file to do normalization of the coefficients and use the option in the if statement.

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/plot_utils.py
>      for opt_name in sel_opts_names:
No need to commit local debug print messages. Please remove

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/plot_utils.py
>          h_dist_all_events = myfile.Get("%s_all_events_%s" % (config.h_dist_name,
Same as above

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/nn_utils.py
> +    """
for the documentation, we would also like to explain the input parameters of the functions. Please add.

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/nn_utils.py
> +    """
please add also here a documentation of the input parameters

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/nn_utils.py
> +    plt.savefig("NN_training/%s/training_loss.eps" % config.suffix)
in the common config, we have a dedicated directory for plots already. Maybe we can stay consistent throughout the code and use the directories which we already have?

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>          end = timer()
same as before. For normalization of the coefficients, you can use an extra option in the common configs. This appears in several parts of this class.

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>              log_memory_usage(((inputs_val, "Input validation data"),
see above

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
can we move the save_model part outside of the if statement?

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +            #inputs = self.ver_normalize_inputs(inputs, "apply")
see comments above for normalization

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +                inputs[:,i] = pos[:,i]
if you only put there the option to normalize the coefficients, you won't need the gymnastics with the position. Worth a try

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +            model.save(out_filename)
before we were saving the keras model as json + h5 file. Maybe worth considering also for here?

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +        #    model = pickle.load(file)
can we remove the part which is out-commented?

2022-10-12 14:24 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +            self.config.z_range[1] = 248
why 248 instead of 249?

2022-10-14 09:28 UTC, babaht commented on tpcwithdnn/idc_data_validator.py
>          df_single_map["flucCorrRPred"] = loaded_model.predict(inputs).astype('float32')
Hi, do you mean the option to switch on/off the normalization?

2022-10-14 15:59 UTC, babaht commented on tpcwithdnn/data_loader.py
I fixed this part because I was once playing around trying to see if the UNet correction works and found out that this was a deprecated function which only worked for the old data structure. It looks like this function is used only for the UNet correction (which currently no one is working on), so I wouldn't really care whether or not to leave it this way, but if you think that it should be recovered to the state before my commit, I will do so.

2022-10-19 11:55 UTC, ehellbar commented on tpcwithdnn/data_loader.py
I see. It seems I remembered it wrongly or that we changed the directory structure at some point. In this case, please just remove the commented lines.

2022-10-19 11:56 UTC, ehellbar commented on tpcwithdnn/idc_data_validator.py
>          df_single_map["flucCorrRPred"] = loaded_model.predict(inputs).astype('float32')
yes. It will be much easier than to comment/uncomment these lines several time in the code.

2022-10-20 17:53 UTC, babaht commented
Hello, I have made the changes according to your comments and pushed the changes to my repository

2022-10-25 12:11 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>              for i in range(4, inputs.shape[1]):
should this not be range(index_derivative+1,inputs.shape[1]) ?

2022-10-25 12:11 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +        # This means [:,index_derivative] is the imaginary part of the 0th Fourier coeffficent,
[:,index_derivative+2] is c0_imag, right?

2022-10-25 12:11 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>          for i in range(4, inputs.shape[1]):
should this not be range(index_derivative+1,inputs.shape[1]) ?

2022-10-25 12:11 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
> +                inputs[:,i] = pos[:,i]
why normalize `inputs[:, :2]` in `ver_normalize_inputs` when you reset it here again? Can't we just skip normalization of pos?

2022-10-25 12:11 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>          inputs[:,2] = (inputs[:,2] / 125)  - 1 # Map z=0 to -1 and z=250 to 1
you normalize position inputs here but replace it with original values later. why not just skip normalization of position inputs?

2022-10-31 08:36 UTC, babaht commented on tpcwithdnn/xgboost_optimiser.py
>          inputs[:,2] = (inputs[:,2] / 125)  - 1 # Map z=0 to -1 and z=250 to 1
Hello Ernst, 
I tried running the correction without normalizing the input, but then it seems that the neural network cannot make a proper prediction, as you can see in the figure attached below. I personally think this makes enough sense, because the positional coordinates are in a range of O(100) while everything else (i.e., the derivatives and the standardized fourier coefficients) is in a range of somewhere between -1 and 1.

[flucCorrRPred_vs_flucCorrR_colz_noPosNorm.pdf](https://github.com/AliceO2Group/TPCwithDNN/files/9899405/flucCorrRPred_vs_flucCorrR_colz_noPosNorm.pdf)
[flucCorrRPred_vs_flucCorrR_PosNorm.pdf](https://github.com/AliceO2Group/TPCwithDNN/files/9899406/flucCorrRPred_vs_flucCorrR_PosNorm.pdf)

2022-11-08 14:37 UTC, ehellbar commented on tpcwithdnn/xgboost_optimiser.py
>          inputs[:,2] = (inputs[:,2] / 125)  - 1 # Map z=0 to -1 and z=250 to 1
Hello Hitoshi,
ok I see, fair enough. Then let's keep it for the moment. Maybe we should continue our discussion from earlier today and start to rethink the input format for the NN, tailoring it better to the way the NN works.

2022-11-08 14:45 UTC, ehellbar commented
Hello Hitoshi,
I started the CI test. Is there anything else you would like to add to this PR? Otherwise we could finally merge it :)
Regards,
Ernst

2022-11-08 14:46 UTC, ehellbar approved these changes

2022-11-08 14:49 UTC, babaht commented
For now, no. Grid search would take more time and research, and there is nothing I plan to do now which would require the modification of the framework.

2023-02-14 10:56 UTC, ehellbar approved these changes

2023-02-14 14:30 UTC, merged