Update of jupyter notebooks for model evaluation
AliceO2Group/TPCwithDNN pull request #70
Opened 2020-12-16 13:52 UTC by ehellbar

Adding and updating notebooks and helper file for model performance and kernel visualization.

2020-12-16 13:56 UTC, ehellbar commented
These are just some basic examples for plots which can be interesting. Of course, depending on the study or the use case, they need to be modified. I would suggest to create notebooks of similar style for every major study that we perform, e.g. like it was done for the GPU comparison or for the studies with large number of events and different grid sizes as presented by Maja over the last weeks.

2021-02-09 22:43 UTC, saganatt requested changes
Hi Ernst, thank you very much for the update.

I will look more and try to understand the physics interpretation of these plots.

In the meantime, could you check my comments to the code?

2021-02-09 22:43 UTC, saganatt commented on tpcwithdnn/kernel_visualization.py
> +def get_full_charge_response(n_phi, n_r, n_z, model_files, input_dir, \
\ is not needed here, same for other functions

2021-02-09 22:43 UTC, saganatt commented on tpcwithdnn/kernel_visualization.py
> +    arr_r_pos, arr_phi_pos, arr_z_pos, \
you can write just: `arr_r_pos, arr_phi_pos, arr_z_pos, *_ = load_data_original(input_dir, [0,0])`

2021-02-09 22:43 UTC, saganatt commented on tpcwithdnn/kernel_visualization.py
> +    input_single[0, i_phi, i_r, :, 0] = input_sc_mean
Most of the code is repeated, these two lines seem to be the only difference between the 3 functions.
What about defining a single function for data processing + 3 wrappers?

2021-06-23 07:46 UTC, closed without merging